#!bin/sh


[temp]
command=/home/daniel/.config/i3blocks/temp.sh
interval=10

[memory]
command=/home/daniel/.config/i3blocks/memory.sh
interval=20
label=

[time]
command=date +'%H:%M, %e %B'
interval=5

[battery]
command=/home/daniel/.config/i3blocks/battery.sh
interval=5  

